### ISSUE TITLE
Helm CrashLoopBackOff Issue - Error: Missing option "--mysql-databases" / "-d".

### ISSUE THREAD

**Issue by mynameis-sohee** [Braedon/prometheus-mysql-exporter#22]
When I followed this repo's README.md, I can't resolve this error when using Helm
```
Error: Missing option "--mysql-databases" / "-d".
```

My config.yaml template is like [this](https://github.com/runderwo/runderwo.github.io/blob/273e5075b95a39187edbb349014eee13f2290e2a/helm/prometheus-mysql-exporter/values.yaml).

And when I deploy helm chart, I refer to READMD.md
> helm repo add braedon https://braedon.github.io/helm
> helm repo update
> helm install braedon/prometheus-mysql-exporter --name <release name> \
                                                 --set mysql.server=<mysql server address> \
                                                 --set image.tag=<image tag>.

How can I solve this? Please tell me how to solve it.

**Comment by mynameis-sohee** [comment]
[Solved]

**01. Helm Chart Version**

When I command like below, CHART VERSION is 0.2.0. but, Real latest version is **0.5.0**

```
> helm search repo braedon/prometheus-mysql-exporter
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
braedon/prometheus-mysql-exporter       0.2.0                           Run queries on Mysql and export the results as ...
``` 

---

**02. values.yaml Example**

I'm beginner of K8S, so I was a little confused how to write values.yaml. 
For beginners like me, I share values.yaml example.

```
---
# Default values for prometheus-mysql-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
mysql:
  server: <db_ip_num>:<db_port_num>
  cred: 
    # If you want to write db's connect info(username, password), you have to create k8s secret. and write below.
    secret: <secret_name>
    usernameKey: <secret_key_username>
    passwordKey: <secret_key_password>
  queries: |
            [DEFAULT]
            # How often to run queries.
            QueryIntervalSecs = 15
            # What to do if a query throws an error. One of:
            # * preserve - keep the metrics/values from the last successful run.
            # * drop - remove metrics previously produced by the query.
            # * zero - keep metrics previously produced by the query, but reset their values to 0.
            QueryOnError = drop
            # What to do if a metric produced by the previous run of a query is not present
            # in the current run. One of:
            # * preserve - keep the value of the metric from the last run it was present in.
            # * drop - remove the metric.
            # * zero - keep the metric, but reset its value to 0.
            QueryOnMissing = drop

            # Queries are defined in sections beginning with 'query_'.
            # Characters following this prefix will be used as a prefix for all metrics
            # generated for this query
            [query_test1]
            # Settings that are not specified are inherited from the DEFAULT section.
            # The database to run the query on.
            QueryDatabase = test
            # The SQL SELECT statement to run.
            QueryStatement = SELECT bar, baz, count(*) as ni, max(ekki) as ptang FROM foo GROUP BY bar, baz;
            # A list of result columns to be be exported as metrics. They must be numeric.
            # Any result columns not listed will be used as metric labels instead.
            QueryValueColumns = ni,ptang

            [query_test2]
            # The DEFAULT settings can be overridden.
            QueryIntervalSecs = 5
            QueryOnError = preserve
            QueryOnMissing = zero
            QueryDatabase = test
            QueryStatement = SELECT bar, count(*) as baz FROM foo GROUP BY bar;
            QueryValueColumns = baz

            [query_test3]
            # Run the query at specific times defined using a cron-like format.
            # See https://pypi.org/project/croniter/ for format details.
            # If QueryCron is set QueryIntervalSecs is ignored.
            # This example is 00:03 every night.
            QueryCron = 3 0 * * *
            # The timezone to use when calcuating cron query run times.
            # Defaults to UTC if not specified.
            QueryCronTimezone = Pacific/Auckland
            QueryDatabase = test
            QueryStatement = SELECT bar, count(*) as baz FROM foo GROUP BY bar;
            QueryValueColumns = baz

deployment:
  replicas: 1

pod:
  annotations: {}
  extraVolumes: []

image:
  repository: braedon/prometheus-mysql-exporter
  tag: 0.5.0
  pullPolicy: IfNotPresent

container:
  port: 9207
  portName: prometheus
  extraArgs: []
  extraEnv: []
  extraVolumeMounts: []
  resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

service:
  port: 9207
  portName: prometheus
  annotations: {}
```
